<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <title>接口测试报告</title>
    <meta name="generator" content="HTMLTestRunner 0.8.2.2"/>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
    <link href="http://libs.baidu.com/bootstrap/3.0.3/css/bootstrap.min.css" rel="stylesheet">
    <script src="http://libs.baidu.com/jquery/2.0.0/jquery.min.js"></script>
    <script src="http://libs.baidu.com/bootstrap/3.0.3/js/bootstrap.min.js"></script>
    
<style type="text/css" media="screen">
body        { font-family: Microsoft YaHei,Tahoma,arial,helvetica,sans-serif;padding: 20px; font-size: 120%; }
table       { font-size: 100%; }
/* -- heading ---------------------------------------------------------------------- */
.heading {
    margin-top: 0ex;
    margin-bottom: 1ex;
}
.heading .description {
    margin-top: 4ex;
    margin-bottom: 6ex;
}
/* -- report ------------------------------------------------------------------------ */
#total_row  { font-weight: bold; }
.passCase   { color: #5cb85c; }
.failCase   { color: #d9534f; font-weight: bold; }
.errorCase  { color: #f0ad4e; font-weight: bold; }
.hiddenRow  { display: none; }
.testcase   { margin-left: 2em; }
</style>

</head>
<body >
<script language="javascript" type="text/javascript">
output_list = Array();
/*level 调整增加只显示通过用例的分类 --Findyou
0:Summary //all hiddenRow
1:Failed  //pt hiddenRow, ft none
2:Pass    //pt none, ft hiddenRow
3:All     //pt none, ft none
*/
function showCase(level) {
    trs = document.getElementsByTagName("tr");
    for (var i = 0; i < trs.length; i++) {
        tr = trs[i];
        id = tr.id;
        if (id.substr(0,2) == 'ft') {
            if (level == 2 || level == 0 ) {
                tr.className = 'hiddenRow';
            }
            else {
                tr.className = '';
            }
        }
        if (id.substr(0,2) == 'pt') {
            if (level < 2) {
                tr.className = 'hiddenRow';
            }
            else {
                tr.className = '';
            }
        }
    }
    //加入【详细】切换文字变化 --Findyou
    detail_class=document.getElementsByClassName('detail');
	//console.log(detail_class.length)
	if (level == 3) {
		for (var i = 0; i < detail_class.length; i++){
			detail_class[i].innerHTML="收起"
		}
	}
	else{
			for (var i = 0; i < detail_class.length; i++){
			detail_class[i].innerHTML="详细"
		}
	}
}
function showClassDetail(cid, count) {
    var id_list = Array(count);
    var toHide = 1;
    for (var i = 0; i < count; i++) {
        //ID修改 点 为 下划线 -Findyou
        tid0 = 't' + cid.substr(1) + '_' + (i+1);
        tid = 'f' + tid0;
        tr = document.getElementById(tid);
        if (!tr) {
            tid = 'p' + tid0;
            tr = document.getElementById(tid);
        }
        id_list[i] = tid;
        if (tr.className) {
            toHide = 0;
        }
    }
    for (var i = 0; i < count; i++) {
        tid = id_list[i];
        //修改点击无法收起的BUG，加入【详细】切换文字变化 --Findyou
        if (toHide) {
            document.getElementById(tid).className = 'hiddenRow';
            document.getElementById(cid).innerText = "详细"
        }
        else {
            document.getElementById(tid).className = '';
            document.getElementById(cid).innerText = "收起"
        }
    }
}
function html_escape(s) {
    s = s.replace(/&/g,'&amp;');
    s = s.replace(/</g,'&lt;');
    s = s.replace(/>/g,'&gt;');
    return s;
}
</script>
<div class='heading'>
<h1 style="font-family: Microsoft YaHei">接口测试报告</h1>
<p class='attribute'><strong>测试人员 : </strong> MuSen</p>
<p class='attribute'><strong>开始时间 : </strong> 2019-08-21 22:35:35</p>
<p class='attribute'><strong>合计耗时 : </strong> 0:00:05.770000</p>
<p class='attribute'><strong>测试结果 : </strong> 共 36，错误 36，通过率= 0.00%</p>

<p class='description'>PY18期的第一份测试报告</p>
</div>


<p id='show_detail_line'>
<a class="btn btn-primary" href='javascript:showCase(0)'>概要{ 0.00% }</a>
<a class="btn btn-danger" href='javascript:showCase(1)'>失败{ 0 }</a>
<a class="btn btn-success" href='javascript:showCase(2)'>通过{ 0 }</a>
<a class="btn btn-info" href='javascript:showCase(3)'>所有{ 36 }</a>
</p>
<table id='result_table' class="table table-condensed table-bordered table-hover">
<colgroup>
<col align='left' />
<col align='right' />
<col align='right' />
<col align='right' />
<col align='right' />
<col align='right' />
</colgroup>
<tr id='header_row' class="text-center success" style="font-weight: bold;font-size: 16px;">
    <td>用例集/测试用例</td>
    <td>总计</td>
    <td>通过</td>
    <td>失败</td>
    <td>错误</td>
    <td>详细</td>
</tr>

<tr class='errorClass warning'>
    <td>test_api_recharge_withdraw.RechargeTeseCase: 充值和取现用例类</td>
    <td class="text-center">16</td>
    <td class="text-center">0</td>
    <td class="text-center">0</td>
    <td class="text-center">16</td>
    <td class="text-center"><a href="javascript:showClassDetail('c1',16)" class="detail" id='c1'>详细</a></td>
</tr>

<tr id='ft1_1' class='none'>
    <td class='errorCase'><div class='testcase'>test_register_01: 正常登陆</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft1_1' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft1_1'>错误</button>
    <div id='div_ft1_1' class="collapse">  -->
    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft1_1' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft1_1'>错误</button>
    <div id='div_ft1_1' class="collapse in" align="left">
    <pre>
    
ft1_1: {"status":1,"code":"10001","data":null,"msg":"登录成功"}
Traceback (most recent call last):
  File "D:\PycharmProjects\20190619代码\librarys\ddt.py", line 150, in wrapper
    return func(self, *args, **kwargs)
  File "D:\PycharmProjects\20190619代码\testcases\test_api_recharge_withdraw.py", line 88, in test_register
    self.wb.write_data(row=case.case_id+1,column=10,msg='pass')
  File "D:\PycharmProjects\20190619代码\common\read_excel.py", line 123, in write_data
    self.wb.save(self.file_name)
  File "C:\Python34\lib\site-packages\openpyxl\workbook\workbook.py", line 391, in save
    save_workbook(self, filename)
  File "C:\Python34\lib\site-packages\openpyxl\writer\excel.py", line 282, in save_workbook
    archive = ZipFile(filename, 'w', ZIP_DEFLATED, allowZip64=True)
  File "C:\Python34\lib\zipfile.py", line 923, in __init__
    self.fp = io.open(file, modeDict[mode])
PermissionError: [Errno 13] Permission denied: 'D:\\PycharmProjects\\20190619代码\\data\\cases.xlsx'


    </pre>
    </div>
    </td>
</tr>

<tr id='ft1_2' class='none'>
    <td class='errorCase'><div class='testcase'>test_register_02: 正常充值</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft1_2' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft1_2'>错误</button>
    <div id='div_ft1_2' class="collapse">  -->
    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft1_2' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft1_2'>错误</button>
    <div id='div_ft1_2' class="collapse in" align="left">
    <pre>
    
ft1_2: {"status":1,"code":"10001","data":{"id":83966,"regname":"小蜜蜂","pwd":"61262AC0D6DCBE6E40C3E1E6EB0BD8AF","mobilephone":"13120909378","leaveamount":"-599.56","type":"1","regtime":"2019-06-19 22:02:05.0"},"msg":"充值成功"}
充值前金额806301.00，充值后金额806301.00，充值的金额100.11
Traceback (most recent call last):
  File "D:\PycharmProjects\20190619代码\testcases\test_api_recharge_withdraw.py", line 74, in test_register
    self.assertEqual(money,end_money-start_money)
  File "C:\Python34\lib\unittest\case.py", line 800, in assertEqual
    assertion_func(first, second, msg=msg)
  File "C:\Python34\lib\unittest\case.py", line 793, in _baseAssertEqual
    raise self.failureException(msg)
AssertionError: 100.11 != Decimal('0.00')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\PycharmProjects\20190619代码\librarys\ddt.py", line 150, in wrapper
    return func(self, *args, **kwargs)
  File "D:\PycharmProjects\20190619代码\testcases\test_api_recharge_withdraw.py", line 82, in test_register
    self.wb.write_data(row=case.case_id+1,column=10,msg='failed')
  File "D:\PycharmProjects\20190619代码\common\read_excel.py", line 123, in write_data
    self.wb.save(self.file_name)
  File "C:\Python34\lib\site-packages\openpyxl\workbook\workbook.py", line 391, in save
    save_workbook(self, filename)
  File "C:\Python34\lib\site-packages\openpyxl\writer\excel.py", line 282, in save_workbook
    archive = ZipFile(filename, 'w', ZIP_DEFLATED, allowZip64=True)
  File "C:\Python34\lib\zipfile.py", line 923, in __init__
    self.fp = io.open(file, modeDict[mode])
PermissionError: [Errno 13] Permission denied: 'D:\\PycharmProjects\\20190619代码\\data\\cases.xlsx'


    </pre>
    </div>
    </td>
</tr>

<tr id='ft1_3' class='none'>
    <td class='errorCase'><div class='testcase'>test_register_03: 充值手机号码不存在</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft1_3' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft1_3'>错误</button>
    <div id='div_ft1_3' class="collapse">  -->
    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft1_3' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft1_3'>错误</button>
    <div id='div_ft1_3' class="collapse in" align="left">
    <pre>
    
ft1_3: {"status":0,"code":"20109","data":null,"msg":"手机号码格式不正确"}
Traceback (most recent call last):
  File "D:\PycharmProjects\20190619代码\librarys\ddt.py", line 150, in wrapper
    return func(self, *args, **kwargs)
  File "D:\PycharmProjects\20190619代码\testcases\test_api_recharge_withdraw.py", line 88, in test_register
    self.wb.write_data(row=case.case_id+1,column=10,msg='pass')
  File "D:\PycharmProjects\20190619代码\common\read_excel.py", line 123, in write_data
    self.wb.save(self.file_name)
  File "C:\Python34\lib\site-packages\openpyxl\workbook\workbook.py", line 391, in save
    save_workbook(self, filename)
  File "C:\Python34\lib\site-packages\openpyxl\writer\excel.py", line 282, in save_workbook
    archive = ZipFile(filename, 'w', ZIP_DEFLATED, allowZip64=True)
  File "C:\Python34\lib\zipfile.py", line 923, in __init__
    self.fp = io.open(file, modeDict[mode])
PermissionError: [Errno 13] Permission denied: 'D:\\PycharmProjects\\20190619代码\\data\\cases.xlsx'


    </pre>
    </div>
    </td>
</tr>

<tr id='ft1_4' class='none'>
    <td class='errorCase'><div class='testcase'>test_register_04: 充值金额小数点大于两位</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft1_4' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft1_4'>错误</button>
    <div id='div_ft1_4' class="collapse">  -->
    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft1_4' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft1_4'>错误</button>
    <div id='div_ft1_4' class="collapse in" align="left">
    <pre>
    
ft1_4: {"status":0,"code":"20116","data":null,"msg":"输入金额的金额小数不能超过两位"}
Traceback (most recent call last):
  File "D:\PycharmProjects\20190619代码\librarys\ddt.py", line 150, in wrapper
    return func(self, *args, **kwargs)
  File "D:\PycharmProjects\20190619代码\testcases\test_api_recharge_withdraw.py", line 88, in test_register
    self.wb.write_data(row=case.case_id+1,column=10,msg='pass')
  File "D:\PycharmProjects\20190619代码\common\read_excel.py", line 123, in write_data
    self.wb.save(self.file_name)
  File "C:\Python34\lib\site-packages\openpyxl\workbook\workbook.py", line 391, in save
    save_workbook(self, filename)
  File "C:\Python34\lib\site-packages\openpyxl\writer\excel.py", line 282, in save_workbook
    archive = ZipFile(filename, 'w', ZIP_DEFLATED, allowZip64=True)
  File "C:\Python34\lib\zipfile.py", line 923, in __init__
    self.fp = io.open(file, modeDict[mode])
PermissionError: [Errno 13] Permission denied: 'D:\\PycharmProjects\\20190619代码\\data\\cases.xlsx'


    </pre>
    </div>
    </td>
</tr>

<tr id='ft1_5' class='none'>
    <td class='errorCase'><div class='testcase'>test_register_05: 充值额度为负数</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft1_5' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft1_5'>错误</button>
    <div id='div_ft1_5' class="collapse">  -->
    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft1_5' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft1_5'>错误</button>
    <div id='div_ft1_5' class="collapse in" align="left">
    <pre>
    
ft1_5: {"status":0,"code":"20117","data":null,"msg":"请输入范围在0到50万之间的正数金额"}
Traceback (most recent call last):
  File "D:\PycharmProjects\20190619代码\librarys\ddt.py", line 150, in wrapper
    return func(self, *args, **kwargs)
  File "D:\PycharmProjects\20190619代码\testcases\test_api_recharge_withdraw.py", line 88, in test_register
    self.wb.write_data(row=case.case_id+1,column=10,msg='pass')
  File "D:\PycharmProjects\20190619代码\common\read_excel.py", line 123, in write_data
    self.wb.save(self.file_name)
  File "C:\Python34\lib\site-packages\openpyxl\workbook\workbook.py", line 391, in save
    save_workbook(self, filename)
  File "C:\Python34\lib\site-packages\openpyxl\writer\excel.py", line 282, in save_workbook
    archive = ZipFile(filename, 'w', ZIP_DEFLATED, allowZip64=True)
  File "C:\Python34\lib\zipfile.py", line 923, in __init__
    self.fp = io.open(file, modeDict[mode])
PermissionError: [Errno 13] Permission denied: 'D:\\PycharmProjects\\20190619代码\\data\\cases.xlsx'


    </pre>
    </div>
    </td>
</tr>

<tr id='ft1_6' class='none'>
    <td class='errorCase'><div class='testcase'>test_register_06: 充值额度为空</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft1_6' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft1_6'>错误</button>
    <div id='div_ft1_6' class="collapse">  -->
    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft1_6' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft1_6'>错误</button>
    <div id='div_ft1_6' class="collapse in" align="left">
    <pre>
    
ft1_6: {"status":0,"code":"20115","data":null,"msg":"请输入金额"}
Traceback (most recent call last):
  File "D:\PycharmProjects\20190619代码\librarys\ddt.py", line 150, in wrapper
    return func(self, *args, **kwargs)
  File "D:\PycharmProjects\20190619代码\testcases\test_api_recharge_withdraw.py", line 88, in test_register
    self.wb.write_data(row=case.case_id+1,column=10,msg='pass')
  File "D:\PycharmProjects\20190619代码\common\read_excel.py", line 123, in write_data
    self.wb.save(self.file_name)
  File "C:\Python34\lib\site-packages\openpyxl\workbook\workbook.py", line 391, in save
    save_workbook(self, filename)
  File "C:\Python34\lib\site-packages\openpyxl\writer\excel.py", line 282, in save_workbook
    archive = ZipFile(filename, 'w', ZIP_DEFLATED, allowZip64=True)
  File "C:\Python34\lib\zipfile.py", line 923, in __init__
    self.fp = io.open(file, modeDict[mode])
PermissionError: [Errno 13] Permission denied: 'D:\\PycharmProjects\\20190619代码\\data\\cases.xlsx'


    </pre>
    </div>
    </td>
</tr>

<tr id='ft1_7' class='none'>
    <td class='errorCase'><div class='testcase'>test_register_07: 充值失败，充值额度大于50万</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft1_7' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft1_7'>错误</button>
    <div id='div_ft1_7' class="collapse">  -->
    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft1_7' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft1_7'>错误</button>
    <div id='div_ft1_7' class="collapse in" align="left">
    <pre>
    
ft1_7: {"status":0,"code":"20117","data":null,"msg":"请输入范围在0到50万之间的正数金额"}
Traceback (most recent call last):
  File "D:\PycharmProjects\20190619代码\librarys\ddt.py", line 150, in wrapper
    return func(self, *args, **kwargs)
  File "D:\PycharmProjects\20190619代码\testcases\test_api_recharge_withdraw.py", line 88, in test_register
    self.wb.write_data(row=case.case_id+1,column=10,msg='pass')
  File "D:\PycharmProjects\20190619代码\common\read_excel.py", line 123, in write_data
    self.wb.save(self.file_name)
  File "C:\Python34\lib\site-packages\openpyxl\workbook\workbook.py", line 391, in save
    save_workbook(self, filename)
  File "C:\Python34\lib\site-packages\openpyxl\writer\excel.py", line 282, in save_workbook
    archive = ZipFile(filename, 'w', ZIP_DEFLATED, allowZip64=True)
  File "C:\Python34\lib\zipfile.py", line 923, in __init__
    self.fp = io.open(file, modeDict[mode])
PermissionError: [Errno 13] Permission denied: 'D:\\PycharmProjects\\20190619代码\\data\\cases.xlsx'


    </pre>
    </div>
    </td>
</tr>

<tr id='ft1_8' class='none'>
    <td class='errorCase'><div class='testcase'>test_register_08: 充值失败，充值金额小数超过两位</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft1_8' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft1_8'>错误</button>
    <div id='div_ft1_8' class="collapse">  -->
    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft1_8' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft1_8'>错误</button>
    <div id='div_ft1_8' class="collapse in" align="left">
    <pre>
    
ft1_8: {"status":0,"code":"20116","data":null,"msg":"输入金额的金额小数不能超过两位"}
Traceback (most recent call last):
  File "D:\PycharmProjects\20190619代码\librarys\ddt.py", line 150, in wrapper
    return func(self, *args, **kwargs)
  File "D:\PycharmProjects\20190619代码\testcases\test_api_recharge_withdraw.py", line 88, in test_register
    self.wb.write_data(row=case.case_id+1,column=10,msg='pass')
  File "D:\PycharmProjects\20190619代码\common\read_excel.py", line 123, in write_data
    self.wb.save(self.file_name)
  File "C:\Python34\lib\site-packages\openpyxl\workbook\workbook.py", line 391, in save
    save_workbook(self, filename)
  File "C:\Python34\lib\site-packages\openpyxl\writer\excel.py", line 282, in save_workbook
    archive = ZipFile(filename, 'w', ZIP_DEFLATED, allowZip64=True)
  File "C:\Python34\lib\zipfile.py", line 923, in __init__
    self.fp = io.open(file, modeDict[mode])
PermissionError: [Errno 13] Permission denied: 'D:\\PycharmProjects\\20190619代码\\data\\cases.xlsx'


    </pre>
    </div>
    </td>
</tr>

<tr id='ft1_9' class='none'>
    <td class='errorCase'><div class='testcase'>test_register_09: 充值失败，充值金额输入的不是数字</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft1_9' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft1_9'>错误</button>
    <div id='div_ft1_9' class="collapse">  -->
    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft1_9' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft1_9'>错误</button>
    <div id='div_ft1_9' class="collapse in" align="left">
    <pre>
    
ft1_9: {"status":0,"code":"20118","data":null,"msg":"请输入数字"}
Traceback (most recent call last):
  File "D:\PycharmProjects\20190619代码\librarys\ddt.py", line 150, in wrapper
    return func(self, *args, **kwargs)
  File "D:\PycharmProjects\20190619代码\testcases\test_api_recharge_withdraw.py", line 88, in test_register
    self.wb.write_data(row=case.case_id+1,column=10,msg='pass')
  File "D:\PycharmProjects\20190619代码\common\read_excel.py", line 123, in write_data
    self.wb.save(self.file_name)
  File "C:\Python34\lib\site-packages\openpyxl\workbook\workbook.py", line 391, in save
    save_workbook(self, filename)
  File "C:\Python34\lib\site-packages\openpyxl\writer\excel.py", line 282, in save_workbook
    archive = ZipFile(filename, 'w', ZIP_DEFLATED, allowZip64=True)
  File "C:\Python34\lib\zipfile.py", line 923, in __init__
    self.fp = io.open(file, modeDict[mode])
PermissionError: [Errno 13] Permission denied: 'D:\\PycharmProjects\\20190619代码\\data\\cases.xlsx'


    </pre>
    </div>
    </td>
</tr>

<tr id='ft1_10' class='none'>
    <td class='errorCase'><div class='testcase'>test_register_10: 取现成功</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft1_10' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft1_10'>错误</button>
    <div id='div_ft1_10' class="collapse">  -->
    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft1_10' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft1_10'>错误</button>
    <div id='div_ft1_10' class="collapse in" align="left">
    <pre>
    
ft1_10: {"status":1,"code":"20119","data":null,"msg":"余额不足，请修改提现额度"}
Traceback (most recent call last):
  File "D:\PycharmProjects\20190619代码\testcases\test_api_recharge_withdraw.py", line 65, in test_register
    self.assertEqual(str(case.excepted),response.json()['code'])
  File "C:\Python34\lib\unittest\case.py", line 800, in assertEqual
    assertion_func(first, second, msg=msg)
  File "C:\Python34\lib\unittest\case.py", line 1173, in assertMultiLineEqual
    self.fail(self._formatMessage(msg, standardMsg))
  File "C:\Python34\lib\unittest\case.py", line 645, in fail
    raise self.failureException(msg)
AssertionError: '10001' != '20119'
- 10001
+ 20119


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\PycharmProjects\20190619代码\librarys\ddt.py", line 150, in wrapper
    return func(self, *args, **kwargs)
  File "D:\PycharmProjects\20190619代码\testcases\test_api_recharge_withdraw.py", line 82, in test_register
    self.wb.write_data(row=case.case_id+1,column=10,msg='failed')
  File "D:\PycharmProjects\20190619代码\common\read_excel.py", line 123, in write_data
    self.wb.save(self.file_name)
  File "C:\Python34\lib\site-packages\openpyxl\workbook\workbook.py", line 391, in save
    save_workbook(self, filename)
  File "C:\Python34\lib\site-packages\openpyxl\writer\excel.py", line 282, in save_workbook
    archive = ZipFile(filename, 'w', ZIP_DEFLATED, allowZip64=True)
  File "C:\Python34\lib\zipfile.py", line 923, in __init__
    self.fp = io.open(file, modeDict[mode])
PermissionError: [Errno 13] Permission denied: 'D:\\PycharmProjects\\20190619代码\\data\\cases.xlsx'


    </pre>
    </div>
    </td>
</tr>

<tr id='ft1_11' class='none'>
    <td class='errorCase'><div class='testcase'>test_register_11: 取现失败，手机号为空</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft1_11' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft1_11'>错误</button>
    <div id='div_ft1_11' class="collapse">  -->
    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft1_11' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft1_11'>错误</button>
    <div id='div_ft1_11' class="collapse in" align="left">
    <pre>
    
ft1_11: {"status":0,"code":"20103","data":null,"msg":"手机号不能为空"}
Traceback (most recent call last):
  File "D:\PycharmProjects\20190619代码\librarys\ddt.py", line 150, in wrapper
    return func(self, *args, **kwargs)
  File "D:\PycharmProjects\20190619代码\testcases\test_api_recharge_withdraw.py", line 88, in test_register
    self.wb.write_data(row=case.case_id+1,column=10,msg='pass')
  File "D:\PycharmProjects\20190619代码\common\read_excel.py", line 123, in write_data
    self.wb.save(self.file_name)
  File "C:\Python34\lib\site-packages\openpyxl\workbook\workbook.py", line 391, in save
    save_workbook(self, filename)
  File "C:\Python34\lib\site-packages\openpyxl\writer\excel.py", line 282, in save_workbook
    archive = ZipFile(filename, 'w', ZIP_DEFLATED, allowZip64=True)
  File "C:\Python34\lib\zipfile.py", line 923, in __init__
    self.fp = io.open(file, modeDict[mode])
PermissionError: [Errno 13] Permission denied: 'D:\\PycharmProjects\\20190619代码\\data\\cases.xlsx'


    </pre>
    </div>
    </td>
</tr>

<tr id='ft1_12' class='none'>
    <td class='errorCase'><div class='testcase'>test_register_12: 取现失败，金额为空</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft1_12' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft1_12'>错误</button>
    <div id='div_ft1_12' class="collapse">  -->
    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft1_12' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft1_12'>错误</button>
    <div id='div_ft1_12' class="collapse in" align="left">
    <pre>
    
ft1_12: {"status":0,"code":"20115","data":null,"msg":"请输入金额"}
Traceback (most recent call last):
  File "D:\PycharmProjects\20190619代码\librarys\ddt.py", line 150, in wrapper
    return func(self, *args, **kwargs)
  File "D:\PycharmProjects\20190619代码\testcases\test_api_recharge_withdraw.py", line 88, in test_register
    self.wb.write_data(row=case.case_id+1,column=10,msg='pass')
  File "D:\PycharmProjects\20190619代码\common\read_excel.py", line 123, in write_data
    self.wb.save(self.file_name)
  File "C:\Python34\lib\site-packages\openpyxl\workbook\workbook.py", line 391, in save
    save_workbook(self, filename)
  File "C:\Python34\lib\site-packages\openpyxl\writer\excel.py", line 282, in save_workbook
    archive = ZipFile(filename, 'w', ZIP_DEFLATED, allowZip64=True)
  File "C:\Python34\lib\zipfile.py", line 923, in __init__
    self.fp = io.open(file, modeDict[mode])
PermissionError: [Errno 13] Permission denied: 'D:\\PycharmProjects\\20190619代码\\data\\cases.xlsx'


    </pre>
    </div>
    </td>
</tr>

<tr id='ft1_13' class='none'>
    <td class='errorCase'><div class='testcase'>test_register_13: 取现失败，金额不大于0</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft1_13' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft1_13'>错误</button>
    <div id='div_ft1_13' class="collapse">  -->
    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft1_13' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft1_13'>错误</button>
    <div id='div_ft1_13' class="collapse in" align="left">
    <pre>
    
ft1_13: {"status":0,"code":"20117","data":null,"msg":"请输入范围在0到50万之间的正数金额"}
Traceback (most recent call last):
  File "D:\PycharmProjects\20190619代码\librarys\ddt.py", line 150, in wrapper
    return func(self, *args, **kwargs)
  File "D:\PycharmProjects\20190619代码\testcases\test_api_recharge_withdraw.py", line 88, in test_register
    self.wb.write_data(row=case.case_id+1,column=10,msg='pass')
  File "D:\PycharmProjects\20190619代码\common\read_excel.py", line 123, in write_data
    self.wb.save(self.file_name)
  File "C:\Python34\lib\site-packages\openpyxl\workbook\workbook.py", line 391, in save
    save_workbook(self, filename)
  File "C:\Python34\lib\site-packages\openpyxl\writer\excel.py", line 282, in save_workbook
    archive = ZipFile(filename, 'w', ZIP_DEFLATED, allowZip64=True)
  File "C:\Python34\lib\zipfile.py", line 923, in __init__
    self.fp = io.open(file, modeDict[mode])
PermissionError: [Errno 13] Permission denied: 'D:\\PycharmProjects\\20190619代码\\data\\cases.xlsx'


    </pre>
    </div>
    </td>
</tr>

<tr id='ft1_14' class='none'>
    <td class='errorCase'><div class='testcase'>test_register_14: 取现失败，金额大于50万</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft1_14' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft1_14'>错误</button>
    <div id='div_ft1_14' class="collapse">  -->
    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft1_14' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft1_14'>错误</button>
    <div id='div_ft1_14' class="collapse in" align="left">
    <pre>
    
ft1_14: {"status":0,"code":"20117","data":null,"msg":"请输入范围在0到50万之间的正数金额"}
Traceback (most recent call last):
  File "D:\PycharmProjects\20190619代码\librarys\ddt.py", line 150, in wrapper
    return func(self, *args, **kwargs)
  File "D:\PycharmProjects\20190619代码\testcases\test_api_recharge_withdraw.py", line 88, in test_register
    self.wb.write_data(row=case.case_id+1,column=10,msg='pass')
  File "D:\PycharmProjects\20190619代码\common\read_excel.py", line 123, in write_data
    self.wb.save(self.file_name)
  File "C:\Python34\lib\site-packages\openpyxl\workbook\workbook.py", line 391, in save
    save_workbook(self, filename)
  File "C:\Python34\lib\site-packages\openpyxl\writer\excel.py", line 282, in save_workbook
    archive = ZipFile(filename, 'w', ZIP_DEFLATED, allowZip64=True)
  File "C:\Python34\lib\zipfile.py", line 923, in __init__
    self.fp = io.open(file, modeDict[mode])
PermissionError: [Errno 13] Permission denied: 'D:\\PycharmProjects\\20190619代码\\data\\cases.xlsx'


    </pre>
    </div>
    </td>
</tr>

<tr id='ft1_15' class='none'>
    <td class='errorCase'><div class='testcase'>test_register_15: 取现失败，金额小数超过两位</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft1_15' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft1_15'>错误</button>
    <div id='div_ft1_15' class="collapse">  -->
    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft1_15' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft1_15'>错误</button>
    <div id='div_ft1_15' class="collapse in" align="left">
    <pre>
    
ft1_15: {"status":0,"code":"20116","data":null,"msg":"输入金额的金额小数不能超过两位"}
Traceback (most recent call last):
  File "D:\PycharmProjects\20190619代码\librarys\ddt.py", line 150, in wrapper
    return func(self, *args, **kwargs)
  File "D:\PycharmProjects\20190619代码\testcases\test_api_recharge_withdraw.py", line 88, in test_register
    self.wb.write_data(row=case.case_id+1,column=10,msg='pass')
  File "D:\PycharmProjects\20190619代码\common\read_excel.py", line 123, in write_data
    self.wb.save(self.file_name)
  File "C:\Python34\lib\site-packages\openpyxl\workbook\workbook.py", line 391, in save
    save_workbook(self, filename)
  File "C:\Python34\lib\site-packages\openpyxl\writer\excel.py", line 282, in save_workbook
    archive = ZipFile(filename, 'w', ZIP_DEFLATED, allowZip64=True)
  File "C:\Python34\lib\zipfile.py", line 923, in __init__
    self.fp = io.open(file, modeDict[mode])
PermissionError: [Errno 13] Permission denied: 'D:\\PycharmProjects\\20190619代码\\data\\cases.xlsx'


    </pre>
    </div>
    </td>
</tr>

<tr id='ft1_16' class='none'>
    <td class='errorCase'><div class='testcase'>test_register_16: 取现失败，金额不是数字</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft1_16' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft1_16'>错误</button>
    <div id='div_ft1_16' class="collapse">  -->
    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft1_16' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft1_16'>错误</button>
    <div id='div_ft1_16' class="collapse in" align="left">
    <pre>
    
ft1_16: {"status":0,"code":"20118","data":null,"msg":"请输入数字"}
Traceback (most recent call last):
  File "D:\PycharmProjects\20190619代码\librarys\ddt.py", line 150, in wrapper
    return func(self, *args, **kwargs)
  File "D:\PycharmProjects\20190619代码\testcases\test_api_recharge_withdraw.py", line 88, in test_register
    self.wb.write_data(row=case.case_id+1,column=10,msg='pass')
  File "D:\PycharmProjects\20190619代码\common\read_excel.py", line 123, in write_data
    self.wb.save(self.file_name)
  File "C:\Python34\lib\site-packages\openpyxl\workbook\workbook.py", line 391, in save
    save_workbook(self, filename)
  File "C:\Python34\lib\site-packages\openpyxl\writer\excel.py", line 282, in save_workbook
    archive = ZipFile(filename, 'w', ZIP_DEFLATED, allowZip64=True)
  File "C:\Python34\lib\zipfile.py", line 923, in __init__
    self.fp = io.open(file, modeDict[mode])
PermissionError: [Errno 13] Permission denied: 'D:\\PycharmProjects\\20190619代码\\data\\cases.xlsx'


    </pre>
    </div>
    </td>
</tr>

<tr class='errorClass warning'>
    <td>test_api_register_login.LoginTestCase: 登陆接口用例类</td>
    <td class="text-center">9</td>
    <td class="text-center">0</td>
    <td class="text-center">0</td>
    <td class="text-center">9</td>
    <td class="text-center"><a href="javascript:showClassDetail('c2',9)" class="detail" id='c2'>详细</a></td>
</tr>

<tr id='ft2_1' class='none'>
    <td class='errorCase'><div class='testcase'>test_login_1: 成功登录</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft2_1' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft2_1'>错误</button>
    <div id='div_ft2_1' class="collapse">  -->
    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft2_1' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft2_1'>错误</button>
    <div id='div_ft2_1' class="collapse in" align="left">
    <pre>
    
ft2_1: Traceback (most recent call last):
  File "D:\PycharmProjects\20190619代码\librarys\ddt.py", line 150, in wrapper
    return func(self, *args, **kwargs)
  File "D:\PycharmProjects\20190619代码\testcases\test_api_register_login.py", line 128, in test_login
    self.wb.write_data(row=case.case_id + 1, column=8, msg='pass')
  File "D:\PycharmProjects\20190619代码\common\read_excel.py", line 123, in write_data
    self.wb.save(self.file_name)
  File "C:\Python34\lib\site-packages\openpyxl\workbook\workbook.py", line 391, in save
    save_workbook(self, filename)
  File "C:\Python34\lib\site-packages\openpyxl\writer\excel.py", line 282, in save_workbook
    archive = ZipFile(filename, 'w', ZIP_DEFLATED, allowZip64=True)
  File "C:\Python34\lib\zipfile.py", line 923, in __init__
    self.fp = io.open(file, modeDict[mode])
PermissionError: [Errno 13] Permission denied: 'D:\\PycharmProjects\\20190619代码\\data\\cases.xlsx'


    </pre>
    </div>
    </td>
</tr>

<tr id='ft2_2' class='none'>
    <td class='errorCase'><div class='testcase'>test_login_2: 手机号为空</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft2_2' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft2_2'>错误</button>
    <div id='div_ft2_2' class="collapse">  -->
    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft2_2' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft2_2'>错误</button>
    <div id='div_ft2_2' class="collapse in" align="left">
    <pre>
    
ft2_2: Traceback (most recent call last):
  File "D:\PycharmProjects\20190619代码\librarys\ddt.py", line 150, in wrapper
    return func(self, *args, **kwargs)
  File "D:\PycharmProjects\20190619代码\testcases\test_api_register_login.py", line 128, in test_login
    self.wb.write_data(row=case.case_id + 1, column=8, msg='pass')
  File "D:\PycharmProjects\20190619代码\common\read_excel.py", line 123, in write_data
    self.wb.save(self.file_name)
  File "C:\Python34\lib\site-packages\openpyxl\workbook\workbook.py", line 391, in save
    save_workbook(self, filename)
  File "C:\Python34\lib\site-packages\openpyxl\writer\excel.py", line 282, in save_workbook
    archive = ZipFile(filename, 'w', ZIP_DEFLATED, allowZip64=True)
  File "C:\Python34\lib\zipfile.py", line 923, in __init__
    self.fp = io.open(file, modeDict[mode])
PermissionError: [Errno 13] Permission denied: 'D:\\PycharmProjects\\20190619代码\\data\\cases.xlsx'


    </pre>
    </div>
    </td>
</tr>

<tr id='ft2_3' class='none'>
    <td class='errorCase'><div class='testcase'>test_login_3: 手机号未注册</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft2_3' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft2_3'>错误</button>
    <div id='div_ft2_3' class="collapse">  -->
    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft2_3' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft2_3'>错误</button>
    <div id='div_ft2_3' class="collapse in" align="left">
    <pre>
    
ft2_3: Traceback (most recent call last):
  File "D:\PycharmProjects\20190619代码\librarys\ddt.py", line 150, in wrapper
    return func(self, *args, **kwargs)
  File "D:\PycharmProjects\20190619代码\testcases\test_api_register_login.py", line 128, in test_login
    self.wb.write_data(row=case.case_id + 1, column=8, msg='pass')
  File "D:\PycharmProjects\20190619代码\common\read_excel.py", line 123, in write_data
    self.wb.save(self.file_name)
  File "C:\Python34\lib\site-packages\openpyxl\workbook\workbook.py", line 391, in save
    save_workbook(self, filename)
  File "C:\Python34\lib\site-packages\openpyxl\writer\excel.py", line 282, in save_workbook
    archive = ZipFile(filename, 'w', ZIP_DEFLATED, allowZip64=True)
  File "C:\Python34\lib\zipfile.py", line 923, in __init__
    self.fp = io.open(file, modeDict[mode])
PermissionError: [Errno 13] Permission denied: 'D:\\PycharmProjects\\20190619代码\\data\\cases.xlsx'


    </pre>
    </div>
    </td>
</tr>

<tr id='ft2_4' class='none'>
    <td class='errorCase'><div class='testcase'>test_login_4: 手机号包含非数字</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft2_4' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft2_4'>错误</button>
    <div id='div_ft2_4' class="collapse">  -->
    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft2_4' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft2_4'>错误</button>
    <div id='div_ft2_4' class="collapse in" align="left">
    <pre>
    
ft2_4: Traceback (most recent call last):
  File "D:\PycharmProjects\20190619代码\librarys\ddt.py", line 150, in wrapper
    return func(self, *args, **kwargs)
  File "D:\PycharmProjects\20190619代码\testcases\test_api_register_login.py", line 128, in test_login
    self.wb.write_data(row=case.case_id + 1, column=8, msg='pass')
  File "D:\PycharmProjects\20190619代码\common\read_excel.py", line 123, in write_data
    self.wb.save(self.file_name)
  File "C:\Python34\lib\site-packages\openpyxl\workbook\workbook.py", line 391, in save
    save_workbook(self, filename)
  File "C:\Python34\lib\site-packages\openpyxl\writer\excel.py", line 282, in save_workbook
    archive = ZipFile(filename, 'w', ZIP_DEFLATED, allowZip64=True)
  File "C:\Python34\lib\zipfile.py", line 923, in __init__
    self.fp = io.open(file, modeDict[mode])
PermissionError: [Errno 13] Permission denied: 'D:\\PycharmProjects\\20190619代码\\data\\cases.xlsx'


    </pre>
    </div>
    </td>
</tr>

<tr id='ft2_5' class='none'>
    <td class='errorCase'><div class='testcase'>test_login_5: 手机号为不合法数字</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft2_5' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft2_5'>错误</button>
    <div id='div_ft2_5' class="collapse">  -->
    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft2_5' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft2_5'>错误</button>
    <div id='div_ft2_5' class="collapse in" align="left">
    <pre>
    
ft2_5: Traceback (most recent call last):
  File "D:\PycharmProjects\20190619代码\librarys\ddt.py", line 150, in wrapper
    return func(self, *args, **kwargs)
  File "D:\PycharmProjects\20190619代码\testcases\test_api_register_login.py", line 128, in test_login
    self.wb.write_data(row=case.case_id + 1, column=8, msg='pass')
  File "D:\PycharmProjects\20190619代码\common\read_excel.py", line 123, in write_data
    self.wb.save(self.file_name)
  File "C:\Python34\lib\site-packages\openpyxl\workbook\workbook.py", line 391, in save
    save_workbook(self, filename)
  File "C:\Python34\lib\site-packages\openpyxl\writer\excel.py", line 282, in save_workbook
    archive = ZipFile(filename, 'w', ZIP_DEFLATED, allowZip64=True)
  File "C:\Python34\lib\zipfile.py", line 923, in __init__
    self.fp = io.open(file, modeDict[mode])
PermissionError: [Errno 13] Permission denied: 'D:\\PycharmProjects\\20190619代码\\data\\cases.xlsx'


    </pre>
    </div>
    </td>
</tr>

<tr id='ft2_6' class='none'>
    <td class='errorCase'><div class='testcase'>test_login_6: 手机号长度不足11位</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft2_6' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft2_6'>错误</button>
    <div id='div_ft2_6' class="collapse">  -->
    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft2_6' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft2_6'>错误</button>
    <div id='div_ft2_6' class="collapse in" align="left">
    <pre>
    
ft2_6: Traceback (most recent call last):
  File "D:\PycharmProjects\20190619代码\librarys\ddt.py", line 150, in wrapper
    return func(self, *args, **kwargs)
  File "D:\PycharmProjects\20190619代码\testcases\test_api_register_login.py", line 128, in test_login
    self.wb.write_data(row=case.case_id + 1, column=8, msg='pass')
  File "D:\PycharmProjects\20190619代码\common\read_excel.py", line 123, in write_data
    self.wb.save(self.file_name)
  File "C:\Python34\lib\site-packages\openpyxl\workbook\workbook.py", line 391, in save
    save_workbook(self, filename)
  File "C:\Python34\lib\site-packages\openpyxl\writer\excel.py", line 282, in save_workbook
    archive = ZipFile(filename, 'w', ZIP_DEFLATED, allowZip64=True)
  File "C:\Python34\lib\zipfile.py", line 923, in __init__
    self.fp = io.open(file, modeDict[mode])
PermissionError: [Errno 13] Permission denied: 'D:\\PycharmProjects\\20190619代码\\data\\cases.xlsx'


    </pre>
    </div>
    </td>
</tr>

<tr id='ft2_7' class='none'>
    <td class='errorCase'><div class='testcase'>test_login_7: 手机号长度超过11位</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft2_7' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft2_7'>错误</button>
    <div id='div_ft2_7' class="collapse">  -->
    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft2_7' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft2_7'>错误</button>
    <div id='div_ft2_7' class="collapse in" align="left">
    <pre>
    
ft2_7: Traceback (most recent call last):
  File "D:\PycharmProjects\20190619代码\librarys\ddt.py", line 150, in wrapper
    return func(self, *args, **kwargs)
  File "D:\PycharmProjects\20190619代码\testcases\test_api_register_login.py", line 128, in test_login
    self.wb.write_data(row=case.case_id + 1, column=8, msg='pass')
  File "D:\PycharmProjects\20190619代码\common\read_excel.py", line 123, in write_data
    self.wb.save(self.file_name)
  File "C:\Python34\lib\site-packages\openpyxl\workbook\workbook.py", line 391, in save
    save_workbook(self, filename)
  File "C:\Python34\lib\site-packages\openpyxl\writer\excel.py", line 282, in save_workbook
    archive = ZipFile(filename, 'w', ZIP_DEFLATED, allowZip64=True)
  File "C:\Python34\lib\zipfile.py", line 923, in __init__
    self.fp = io.open(file, modeDict[mode])
PermissionError: [Errno 13] Permission denied: 'D:\\PycharmProjects\\20190619代码\\data\\cases.xlsx'


    </pre>
    </div>
    </td>
</tr>

<tr id='ft2_8' class='none'>
    <td class='errorCase'><div class='testcase'>test_login_8: 密码为空</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft2_8' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft2_8'>错误</button>
    <div id='div_ft2_8' class="collapse">  -->
    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft2_8' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft2_8'>错误</button>
    <div id='div_ft2_8' class="collapse in" align="left">
    <pre>
    
ft2_8: Traceback (most recent call last):
  File "D:\PycharmProjects\20190619代码\librarys\ddt.py", line 150, in wrapper
    return func(self, *args, **kwargs)
  File "D:\PycharmProjects\20190619代码\testcases\test_api_register_login.py", line 128, in test_login
    self.wb.write_data(row=case.case_id + 1, column=8, msg='pass')
  File "D:\PycharmProjects\20190619代码\common\read_excel.py", line 123, in write_data
    self.wb.save(self.file_name)
  File "C:\Python34\lib\site-packages\openpyxl\workbook\workbook.py", line 391, in save
    save_workbook(self, filename)
  File "C:\Python34\lib\site-packages\openpyxl\writer\excel.py", line 282, in save_workbook
    archive = ZipFile(filename, 'w', ZIP_DEFLATED, allowZip64=True)
  File "C:\Python34\lib\zipfile.py", line 923, in __init__
    self.fp = io.open(file, modeDict[mode])
PermissionError: [Errno 13] Permission denied: 'D:\\PycharmProjects\\20190619代码\\data\\cases.xlsx'


    </pre>
    </div>
    </td>
</tr>

<tr id='ft2_9' class='none'>
    <td class='errorCase'><div class='testcase'>test_login_9: 密码错误</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft2_9' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft2_9'>错误</button>
    <div id='div_ft2_9' class="collapse">  -->
    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft2_9' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft2_9'>错误</button>
    <div id='div_ft2_9' class="collapse in" align="left">
    <pre>
    
ft2_9: Traceback (most recent call last):
  File "D:\PycharmProjects\20190619代码\librarys\ddt.py", line 150, in wrapper
    return func(self, *args, **kwargs)
  File "D:\PycharmProjects\20190619代码\testcases\test_api_register_login.py", line 128, in test_login
    self.wb.write_data(row=case.case_id + 1, column=8, msg='pass')
  File "D:\PycharmProjects\20190619代码\common\read_excel.py", line 123, in write_data
    self.wb.save(self.file_name)
  File "C:\Python34\lib\site-packages\openpyxl\workbook\workbook.py", line 391, in save
    save_workbook(self, filename)
  File "C:\Python34\lib\site-packages\openpyxl\writer\excel.py", line 282, in save_workbook
    archive = ZipFile(filename, 'w', ZIP_DEFLATED, allowZip64=True)
  File "C:\Python34\lib\zipfile.py", line 923, in __init__
    self.fp = io.open(file, modeDict[mode])
PermissionError: [Errno 13] Permission denied: 'D:\\PycharmProjects\\20190619代码\\data\\cases.xlsx'


    </pre>
    </div>
    </td>
</tr>

<tr class='errorClass warning'>
    <td>test_api_register_login.RegisterTeseCase: 注册接口用例类</td>
    <td class="text-center">11</td>
    <td class="text-center">0</td>
    <td class="text-center">0</td>
    <td class="text-center">11</td>
    <td class="text-center"><a href="javascript:showClassDetail('c3',11)" class="detail" id='c3'>详细</a></td>
</tr>

<tr id='ft3_1' class='none'>
    <td class='errorCase'><div class='testcase'>test_register_01: 成功注册(有昵称)</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft3_1' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft3_1'>错误</button>
    <div id='div_ft3_1' class="collapse">  -->
    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft3_1' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft3_1'>错误</button>
    <div id='div_ft3_1' class="collapse in" align="left">
    <pre>
    
ft3_1: 13466834138
Traceback (most recent call last):
  File "D:\PycharmProjects\20190619代码\librarys\ddt.py", line 150, in wrapper
    return func(self, *args, **kwargs)
  File "D:\PycharmProjects\20190619代码\testcases\test_api_register_login.py", line 87, in test_register
    self.wb.write_data(row=case.case_id + 1, column=8, msg='pass')
  File "D:\PycharmProjects\20190619代码\common\read_excel.py", line 123, in write_data
    self.wb.save(self.file_name)
  File "C:\Python34\lib\site-packages\openpyxl\workbook\workbook.py", line 391, in save
    save_workbook(self, filename)
  File "C:\Python34\lib\site-packages\openpyxl\writer\excel.py", line 282, in save_workbook
    archive = ZipFile(filename, 'w', ZIP_DEFLATED, allowZip64=True)
  File "C:\Python34\lib\zipfile.py", line 923, in __init__
    self.fp = io.open(file, modeDict[mode])
PermissionError: [Errno 13] Permission denied: 'D:\\PycharmProjects\\20190619代码\\data\\cases.xlsx'


    </pre>
    </div>
    </td>
</tr>

<tr id='ft3_2' class='none'>
    <td class='errorCase'><div class='testcase'>test_register_02: 成功注册(无昵称)</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft3_2' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft3_2'>错误</button>
    <div id='div_ft3_2' class="collapse">  -->
    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft3_2' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft3_2'>错误</button>
    <div id='div_ft3_2' class="collapse in" align="left">
    <pre>
    
ft3_2: 13499021710
Traceback (most recent call last):
  File "D:\PycharmProjects\20190619代码\librarys\ddt.py", line 150, in wrapper
    return func(self, *args, **kwargs)
  File "D:\PycharmProjects\20190619代码\testcases\test_api_register_login.py", line 87, in test_register
    self.wb.write_data(row=case.case_id + 1, column=8, msg='pass')
  File "D:\PycharmProjects\20190619代码\common\read_excel.py", line 123, in write_data
    self.wb.save(self.file_name)
  File "C:\Python34\lib\site-packages\openpyxl\workbook\workbook.py", line 391, in save
    save_workbook(self, filename)
  File "C:\Python34\lib\site-packages\openpyxl\writer\excel.py", line 282, in save_workbook
    archive = ZipFile(filename, 'w', ZIP_DEFLATED, allowZip64=True)
  File "C:\Python34\lib\zipfile.py", line 923, in __init__
    self.fp = io.open(file, modeDict[mode])
PermissionError: [Errno 13] Permission denied: 'D:\\PycharmProjects\\20190619代码\\data\\cases.xlsx'


    </pre>
    </div>
    </td>
</tr>

<tr id='ft3_3' class='none'>
    <td class='errorCase'><div class='testcase'>test_register_03: 手机号已被注册</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft3_3' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft3_3'>错误</button>
    <div id='div_ft3_3' class="collapse">  -->
    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft3_3' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft3_3'>错误</button>
    <div id='div_ft3_3' class="collapse in" align="left">
    <pre>
    
ft3_3: Traceback (most recent call last):
  File "D:\PycharmProjects\20190619代码\librarys\ddt.py", line 150, in wrapper
    return func(self, *args, **kwargs)
  File "D:\PycharmProjects\20190619代码\testcases\test_api_register_login.py", line 87, in test_register
    self.wb.write_data(row=case.case_id + 1, column=8, msg='pass')
  File "D:\PycharmProjects\20190619代码\common\read_excel.py", line 123, in write_data
    self.wb.save(self.file_name)
  File "C:\Python34\lib\site-packages\openpyxl\workbook\workbook.py", line 391, in save
    save_workbook(self, filename)
  File "C:\Python34\lib\site-packages\openpyxl\writer\excel.py", line 282, in save_workbook
    archive = ZipFile(filename, 'w', ZIP_DEFLATED, allowZip64=True)
  File "C:\Python34\lib\zipfile.py", line 923, in __init__
    self.fp = io.open(file, modeDict[mode])
PermissionError: [Errno 13] Permission denied: 'D:\\PycharmProjects\\20190619代码\\data\\cases.xlsx'


    </pre>
    </div>
    </td>
</tr>

<tr id='ft3_4' class='none'>
    <td class='errorCase'><div class='testcase'>test_register_04: 手机号为空</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft3_4' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft3_4'>错误</button>
    <div id='div_ft3_4' class="collapse">  -->
    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft3_4' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft3_4'>错误</button>
    <div id='div_ft3_4' class="collapse in" align="left">
    <pre>
    
ft3_4: Traceback (most recent call last):
  File "D:\PycharmProjects\20190619代码\librarys\ddt.py", line 150, in wrapper
    return func(self, *args, **kwargs)
  File "D:\PycharmProjects\20190619代码\testcases\test_api_register_login.py", line 87, in test_register
    self.wb.write_data(row=case.case_id + 1, column=8, msg='pass')
  File "D:\PycharmProjects\20190619代码\common\read_excel.py", line 123, in write_data
    self.wb.save(self.file_name)
  File "C:\Python34\lib\site-packages\openpyxl\workbook\workbook.py", line 391, in save
    save_workbook(self, filename)
  File "C:\Python34\lib\site-packages\openpyxl\writer\excel.py", line 282, in save_workbook
    archive = ZipFile(filename, 'w', ZIP_DEFLATED, allowZip64=True)
  File "C:\Python34\lib\zipfile.py", line 923, in __init__
    self.fp = io.open(file, modeDict[mode])
PermissionError: [Errno 13] Permission denied: 'D:\\PycharmProjects\\20190619代码\\data\\cases.xlsx'


    </pre>
    </div>
    </td>
</tr>

<tr id='ft3_5' class='none'>
    <td class='errorCase'><div class='testcase'>test_register_05: 手机号长度不足11位</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft3_5' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft3_5'>错误</button>
    <div id='div_ft3_5' class="collapse">  -->
    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft3_5' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft3_5'>错误</button>
    <div id='div_ft3_5' class="collapse in" align="left">
    <pre>
    
ft3_5: Traceback (most recent call last):
  File "D:\PycharmProjects\20190619代码\librarys\ddt.py", line 150, in wrapper
    return func(self, *args, **kwargs)
  File "D:\PycharmProjects\20190619代码\testcases\test_api_register_login.py", line 87, in test_register
    self.wb.write_data(row=case.case_id + 1, column=8, msg='pass')
  File "D:\PycharmProjects\20190619代码\common\read_excel.py", line 123, in write_data
    self.wb.save(self.file_name)
  File "C:\Python34\lib\site-packages\openpyxl\workbook\workbook.py", line 391, in save
    save_workbook(self, filename)
  File "C:\Python34\lib\site-packages\openpyxl\writer\excel.py", line 282, in save_workbook
    archive = ZipFile(filename, 'w', ZIP_DEFLATED, allowZip64=True)
  File "C:\Python34\lib\zipfile.py", line 923, in __init__
    self.fp = io.open(file, modeDict[mode])
PermissionError: [Errno 13] Permission denied: 'D:\\PycharmProjects\\20190619代码\\data\\cases.xlsx'


    </pre>
    </div>
    </td>
</tr>

<tr id='ft3_6' class='none'>
    <td class='errorCase'><div class='testcase'>test_register_06: 手机号长度超过11位</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft3_6' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft3_6'>错误</button>
    <div id='div_ft3_6' class="collapse">  -->
    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft3_6' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft3_6'>错误</button>
    <div id='div_ft3_6' class="collapse in" align="left">
    <pre>
    
ft3_6: Traceback (most recent call last):
  File "D:\PycharmProjects\20190619代码\librarys\ddt.py", line 150, in wrapper
    return func(self, *args, **kwargs)
  File "D:\PycharmProjects\20190619代码\testcases\test_api_register_login.py", line 87, in test_register
    self.wb.write_data(row=case.case_id + 1, column=8, msg='pass')
  File "D:\PycharmProjects\20190619代码\common\read_excel.py", line 123, in write_data
    self.wb.save(self.file_name)
  File "C:\Python34\lib\site-packages\openpyxl\workbook\workbook.py", line 391, in save
    save_workbook(self, filename)
  File "C:\Python34\lib\site-packages\openpyxl\writer\excel.py", line 282, in save_workbook
    archive = ZipFile(filename, 'w', ZIP_DEFLATED, allowZip64=True)
  File "C:\Python34\lib\zipfile.py", line 923, in __init__
    self.fp = io.open(file, modeDict[mode])
PermissionError: [Errno 13] Permission denied: 'D:\\PycharmProjects\\20190619代码\\data\\cases.xlsx'


    </pre>
    </div>
    </td>
</tr>

<tr id='ft3_7' class='none'>
    <td class='errorCase'><div class='testcase'>test_register_07: 手机号包含非数字</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft3_7' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft3_7'>错误</button>
    <div id='div_ft3_7' class="collapse">  -->
    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft3_7' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft3_7'>错误</button>
    <div id='div_ft3_7' class="collapse in" align="left">
    <pre>
    
ft3_7: Traceback (most recent call last):
  File "D:\PycharmProjects\20190619代码\librarys\ddt.py", line 150, in wrapper
    return func(self, *args, **kwargs)
  File "D:\PycharmProjects\20190619代码\testcases\test_api_register_login.py", line 87, in test_register
    self.wb.write_data(row=case.case_id + 1, column=8, msg='pass')
  File "D:\PycharmProjects\20190619代码\common\read_excel.py", line 123, in write_data
    self.wb.save(self.file_name)
  File "C:\Python34\lib\site-packages\openpyxl\workbook\workbook.py", line 391, in save
    save_workbook(self, filename)
  File "C:\Python34\lib\site-packages\openpyxl\writer\excel.py", line 282, in save_workbook
    archive = ZipFile(filename, 'w', ZIP_DEFLATED, allowZip64=True)
  File "C:\Python34\lib\zipfile.py", line 923, in __init__
    self.fp = io.open(file, modeDict[mode])
PermissionError: [Errno 13] Permission denied: 'D:\\PycharmProjects\\20190619代码\\data\\cases.xlsx'


    </pre>
    </div>
    </td>
</tr>

<tr id='ft3_8' class='none'>
    <td class='errorCase'><div class='testcase'>test_register_08: 不是手机号的11位数</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft3_8' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft3_8'>错误</button>
    <div id='div_ft3_8' class="collapse">  -->
    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft3_8' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft3_8'>错误</button>
    <div id='div_ft3_8' class="collapse in" align="left">
    <pre>
    
ft3_8: Traceback (most recent call last):
  File "D:\PycharmProjects\20190619代码\librarys\ddt.py", line 150, in wrapper
    return func(self, *args, **kwargs)
  File "D:\PycharmProjects\20190619代码\testcases\test_api_register_login.py", line 87, in test_register
    self.wb.write_data(row=case.case_id + 1, column=8, msg='pass')
  File "D:\PycharmProjects\20190619代码\common\read_excel.py", line 123, in write_data
    self.wb.save(self.file_name)
  File "C:\Python34\lib\site-packages\openpyxl\workbook\workbook.py", line 391, in save
    save_workbook(self, filename)
  File "C:\Python34\lib\site-packages\openpyxl\writer\excel.py", line 282, in save_workbook
    archive = ZipFile(filename, 'w', ZIP_DEFLATED, allowZip64=True)
  File "C:\Python34\lib\zipfile.py", line 923, in __init__
    self.fp = io.open(file, modeDict[mode])
PermissionError: [Errno 13] Permission denied: 'D:\\PycharmProjects\\20190619代码\\data\\cases.xlsx'


    </pre>
    </div>
    </td>
</tr>

<tr id='ft3_9' class='none'>
    <td class='errorCase'><div class='testcase'>test_register_09: 密码为空</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft3_9' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft3_9'>错误</button>
    <div id='div_ft3_9' class="collapse">  -->
    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft3_9' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft3_9'>错误</button>
    <div id='div_ft3_9' class="collapse in" align="left">
    <pre>
    
ft3_9: Traceback (most recent call last):
  File "D:\PycharmProjects\20190619代码\librarys\ddt.py", line 150, in wrapper
    return func(self, *args, **kwargs)
  File "D:\PycharmProjects\20190619代码\testcases\test_api_register_login.py", line 87, in test_register
    self.wb.write_data(row=case.case_id + 1, column=8, msg='pass')
  File "D:\PycharmProjects\20190619代码\common\read_excel.py", line 123, in write_data
    self.wb.save(self.file_name)
  File "C:\Python34\lib\site-packages\openpyxl\workbook\workbook.py", line 391, in save
    save_workbook(self, filename)
  File "C:\Python34\lib\site-packages\openpyxl\writer\excel.py", line 282, in save_workbook
    archive = ZipFile(filename, 'w', ZIP_DEFLATED, allowZip64=True)
  File "C:\Python34\lib\zipfile.py", line 923, in __init__
    self.fp = io.open(file, modeDict[mode])
PermissionError: [Errno 13] Permission denied: 'D:\\PycharmProjects\\20190619代码\\data\\cases.xlsx'


    </pre>
    </div>
    </td>
</tr>

<tr id='ft3_10' class='none'>
    <td class='errorCase'><div class='testcase'>test_register_10: 密码长度不足6位</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft3_10' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft3_10'>错误</button>
    <div id='div_ft3_10' class="collapse">  -->
    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft3_10' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft3_10'>错误</button>
    <div id='div_ft3_10' class="collapse in" align="left">
    <pre>
    
ft3_10: Traceback (most recent call last):
  File "D:\PycharmProjects\20190619代码\librarys\ddt.py", line 150, in wrapper
    return func(self, *args, **kwargs)
  File "D:\PycharmProjects\20190619代码\testcases\test_api_register_login.py", line 87, in test_register
    self.wb.write_data(row=case.case_id + 1, column=8, msg='pass')
  File "D:\PycharmProjects\20190619代码\common\read_excel.py", line 123, in write_data
    self.wb.save(self.file_name)
  File "C:\Python34\lib\site-packages\openpyxl\workbook\workbook.py", line 391, in save
    save_workbook(self, filename)
  File "C:\Python34\lib\site-packages\openpyxl\writer\excel.py", line 282, in save_workbook
    archive = ZipFile(filename, 'w', ZIP_DEFLATED, allowZip64=True)
  File "C:\Python34\lib\zipfile.py", line 923, in __init__
    self.fp = io.open(file, modeDict[mode])
PermissionError: [Errno 13] Permission denied: 'D:\\PycharmProjects\\20190619代码\\data\\cases.xlsx'


    </pre>
    </div>
    </td>
</tr>

<tr id='ft3_11' class='none'>
    <td class='errorCase'><div class='testcase'>test_register_11: 密码长度超过18位</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft3_11' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft3_11'>错误</button>
    <div id='div_ft3_11' class="collapse">  -->
    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft3_11' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft3_11'>错误</button>
    <div id='div_ft3_11' class="collapse in" align="left">
    <pre>
    
ft3_11: Traceback (most recent call last):
  File "D:\PycharmProjects\20190619代码\librarys\ddt.py", line 150, in wrapper
    return func(self, *args, **kwargs)
  File "D:\PycharmProjects\20190619代码\testcases\test_api_register_login.py", line 87, in test_register
    self.wb.write_data(row=case.case_id + 1, column=8, msg='pass')
  File "D:\PycharmProjects\20190619代码\common\read_excel.py", line 123, in write_data
    self.wb.save(self.file_name)
  File "C:\Python34\lib\site-packages\openpyxl\workbook\workbook.py", line 391, in save
    save_workbook(self, filename)
  File "C:\Python34\lib\site-packages\openpyxl\writer\excel.py", line 282, in save_workbook
    archive = ZipFile(filename, 'w', ZIP_DEFLATED, allowZip64=True)
  File "C:\Python34\lib\zipfile.py", line 923, in __init__
    self.fp = io.open(file, modeDict[mode])
PermissionError: [Errno 13] Permission denied: 'D:\\PycharmProjects\\20190619代码\\data\\cases.xlsx'


    </pre>
    </div>
    </td>
</tr>

<tr id='total_row' class="text-center active">
    <td>总计</td>
    <td>36</td>
    <td>0</td>
    <td>0</td>
    <td>36</td>
    <td>通过率：0.00%</td>
</tr>
</table>

<div id='ending'>&nbsp;</div>
    <div style=" position:fixed;right:50px; bottom:30px; width:20px; height:20px;cursor:pointer">
    <a href="#"><span class="glyphicon glyphicon-eject" style = "font-size:30px;" aria-hidden="true">
    </span></a></div>
    
</body>
</html>
